"use client";

import { useQuery } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import { listAdminAuditLogs } from "@/api/admin.api";
import { RequirePermission } from "@/auth/require-permission";
import { Button } from "@/components/common/Button";
import { Card } from "@/components/common/Card";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { EmptyState } from "@/components/feedback/EmptyState";
import { ErrorState } from "@/components/feedback/ErrorState";
import { LoadingState } from "@/components/feedback/LoadingState";
import { safeAuditMetadata } from "@/lib/audit-log";
import { queryKeys } from "@/lib/query-keys";
import { formatDateTime } from "@/lib/tasks";
import type { AuditLog } from "@/types/domain";

function AuditLogDetail({ item, onClose }: { item: AuditLog; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const metadata = safeAuditMetadata(item.metadata);
  useEffect(() => { dialog.current?.showModal(); }, []);
  return <dialog ref={dialog} className="m-auto max-h-[90vh] w-[min(720px,calc(100%-2rem))] overflow-y-auto rounded-card border border-border bg-surface p-0 text-foreground shadow-2xl backdrop:bg-slate-950/60" aria-labelledby="audit-detail-title" onClose={onClose}><div className="sticky top-0 flex items-start justify-between gap-3 border-b border-border bg-surface p-5"><div><p className="text-xs font-black tracking-[0.16em] text-primary">CHI TIẾT AUDIT</p><h2 id="audit-detail-title" className="mt-1 text-xl font-black">{item.action || "Hành động hệ thống"}</h2></div><Button variant="ghost" onClick={() => dialog.current?.close()}>Đóng</Button></div><div className="grid gap-5 p-5"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-xs font-bold text-muted-foreground">Thời điểm</dt><dd className="mt-1 break-words">{formatDateTime(item.timestamp ?? item.createdAt ?? undefined)}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Kết quả</dt><dd className="mt-1"><StatusBadge value={item.result || "UNKNOWN"} /></dd></div><div><dt className="text-xs font-bold text-muted-foreground">Actor</dt><dd className="mt-1 break-words">{item.actorName || item.actor || "Hệ thống"}{item.actorRole ? ` · ${item.actorRole}` : ""}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Resource</dt><dd className="mt-1 break-all">{item.entityType || "—"}{item.entityId ? ` · ${item.entityId}` : ""}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Request ID</dt><dd className="mt-1 break-all" translate="no">{item.requestId || "—"}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">IP</dt><dd className="mt-1 break-all" translate="no">{item.ipAddress || "—"}</dd></div></dl>{item.userAgent ? <section><h3 className="font-black">User agent</h3><p className="mt-2 break-words rounded-control bg-surface-muted p-3 text-sm" translate="no">{item.userAgent}</p></section> : null}<section><h3 className="font-black">Metadata an toàn</h3>{metadata.length > 0 ? <dl className="mt-3 grid gap-3">{metadata.map((entry) => <div key={entry.key} className="rounded-control bg-surface-muted p-3"><dt className="text-xs font-bold text-muted-foreground" translate="no">{entry.key}</dt><dd className="mt-1 break-words text-sm">{entry.value}</dd></div>)}</dl> : <p className="mt-2 text-sm text-muted-foreground">Không có metadata an toàn để hiển thị.</p>}</section></div></dialog>;
}

export default function AdminAuditLogsPage() {
  const [selected, setSelected] = useState<AuditLog | null>(null);
  const query = useQuery({ queryKey: queryKeys.adminAuditLogs(), queryFn: listAdminAuditLogs });
  return <RequirePermission permissions={["AUDIT_LOG_VIEW"]}><PageHeader eyebrow="PLATFORM ADMIN" title="Nhật ký hệ thống" description="Danh sách chỉ hiển thị thông tin nhận diện; dữ liệu kỹ thuật an toàn nằm trong chi tiết." />{query.isLoading ? <LoadingState rows={5} /> : null}{query.error ? <ErrorState title="Không thể tải nhật ký hệ thống" error={query.error} onRetry={() => void query.refetch()} /> : null}{!query.isLoading && !query.error ? query.data?.length ? <Card className="p-0"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border bg-surface-subtle text-xs font-bold text-muted-foreground"><th className="px-4 py-3">Thời điểm</th><th className="px-4 py-3">Actor</th><th className="px-4 py-3">Hành động</th><th className="px-4 py-3">Resource</th><th className="px-4 py-3">Kết quả</th><th className="px-4 py-3">Request ID</th><th className="px-4 py-3 text-right">Chi tiết</th></tr></thead><tbody>{query.data.map((item, index) => <tr key={item.id ?? `${item.createdAt}-${index}`} className="border-b border-border last:border-0"><td className="px-4 py-3 text-muted-foreground">{formatDateTime(item.timestamp ?? item.createdAt ?? undefined)}</td><td className="px-4 py-3"><span className="font-semibold">{item.actorName || item.actor || "Hệ thống"}</span><span className="block text-xs text-muted-foreground">{item.actorRole || "—"}</span></td><td className="px-4 py-3 font-semibold">{item.action || "—"}</td><td className="px-4 py-3 text-muted-foreground">{item.entityType || "—"}</td><td className="px-4 py-3"><StatusBadge value={item.result || "UNKNOWN"} /></td><td className="max-w-40 truncate px-4 py-3 text-xs" translate="no">{item.requestId || "—"}</td><td className="px-4 py-3 text-right"><Button variant="ghost" className="min-h-9" onClick={() => setSelected(item)}>Xem</Button></td></tr>)}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{query.data.map((item, index) => <article key={item.id ?? index} className="rounded-control border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{item.action || "Hành động hệ thống"}</p><p className="mt-1 text-sm text-muted-foreground">{item.actorName || item.actor || "Hệ thống"}</p></div><StatusBadge value={item.result || "UNKNOWN"} /></div><p className="mt-3 text-xs text-muted-foreground">{formatDateTime(item.timestamp ?? item.createdAt ?? undefined)}</p><Button variant="secondary" className="mt-3 w-full" onClick={() => setSelected(item)}>Xem chi tiết</Button></article>)}</div></Card> : <EmptyState title="Chưa có nhật ký" description="Backend chưa trả bản ghi audit log nào." /> : null}{selected ? <AuditLogDetail item={selected} onClose={() => setSelected(null)} /> : null}</RequirePermission>;
}