import { useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader.jsx'
import SearchAndFilterBar from '../components/SearchAndFilterBar.jsx'
import EmptyState from '../components/EmptyState.jsx'
import Badge from '../components/ui/Badge.jsx'
import Button from '../components/ui/Button.jsx'
import Card from '../components/ui/Card.jsx'
import ErrorState from '../components/ui/ErrorState.jsx'
import LoadingState from '../components/ui/LoadingState.jsx'
import { useServiceData } from '../hooks/useServiceData.js'
import { deleteNotification, getNotifications, markAllAsRead, markAsRead } from '../services/notificationService.js'
import { extractBackendMessage, getDate, getId, valueOf } from '../services/responseNormalizer.js'

function NotificationPage() {
  const { data: notifications, loading, error, apiPending, retry } = useServiceData(getNotifications, [])
  const [search, setSearch] = useState('')
  const [type, setType] = useState('')
  const [readFilter, setReadFilter] = useState('')
  const [actionMessage, setActionMessage] = useState('')
  const [actionError, setActionError] = useState('')
  const filtered = useMemo(() => notifications.filter((item) => {
    const read = Boolean(item.read ?? item.isRead)
    const itemType = valueOf(item, ['type', 'notificationType'], 'System')
    return `${valueOf(item, ['title'], 'Untitled')} ${valueOf(item, ['message', 'content'], '')}`.toLowerCase().includes(search.toLowerCase()) && (!type || itemType === type) && (!readFilter || (readFilter === 'Unread' ? !read : read))
  }), [notifications, search, type, readFilter])

  const readOne = async (id) => {
    setActionMessage('')
    setActionError('')
    try {
      const response = await markAsRead(id)
      setActionMessage(extractBackendMessage(response, 'Notification marked as read.'))
      retry()
    } catch (err) {
      setActionError(err?.message || 'Unable to update notification.')
    }
  }
  const remove = async (id) => {
    setActionMessage('')
    setActionError('')
    try {
      const response = await deleteNotification(id)
      setActionMessage(extractBackendMessage(response, 'Notification deleted.'))
      retry()
    } catch (err) {
      setActionError(err?.message || 'Unable to delete notification.')
    }
  }
  const readAll = async () => {
    setActionMessage('')
    setActionError('')
    try {
      const response = await markAllAsRead()
      setActionMessage(extractBackendMessage(response, 'Notifications marked as read.'))
      retry()
    } catch (err) {
      setActionError(err?.message || 'Unable to update notifications.')
    }
  }

  return (
    <>
      <PageHeader title="Notification Center" description="Review alerts generated by operational events and account activity." action={<Button variant="secondary" onClick={readAll}>Mark all as read</Button>} />
      {actionMessage ? <p className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-200">{actionMessage}</p> : null}
      {actionError ? <p className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200">{actionError}</p> : null}
      {loading ? <LoadingState /> : null}
      {error ? <ErrorState title="Unable to load notifications" description={error.message} status={error.status} details={error.details} onRetry={retry} /> : null}
      {apiPending ? <ErrorState description="Connect notification APIs to display notifications." onRetry={retry} /> : null}
      {!loading && !error && !apiPending ? (
        <>
          <SearchAndFilterBar search={search} onSearchChange={setSearch} filters={[
            { label: 'All types', value: type, onChange: setType, options: [...new Set(notifications.map((item) => valueOf(item, ['type', 'notificationType'], '')).filter(Boolean))] },
            { label: 'Read status', value: readFilter, onChange: setReadFilter, options: ['Unread', 'Read'] },
          ]} />
          <div className="grid gap-4">{filtered.map((item, index) => {
            const id = getId(item)
            const read = Boolean(item.read ?? item.isRead)
            return <Card key={`${id}-${index}`} className="page-animate opacity-0"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-[var(--text)]">{valueOf(item, ['title'], 'Untitled')}</h2>{!read ? <span className="h-2 w-2 rounded-full bg-[#0ea5e9]" /> : null}</div><p className="mt-2 text-sm text-[var(--muted)]">{valueOf(item, ['message', 'content'], 'No description')}</p><p className="mt-1 text-xs text-[var(--muted)]">{getDate(item)}</p><div className="mt-3 flex gap-2"><Badge tone="Info">{valueOf(item, ['type', 'notificationType'], 'System')}</Badge><Badge tone={read ? 'Success' : 'Warning'}>{read ? 'Read' : 'Unread'}</Badge></div></div><div className="flex gap-2"><Button variant="secondary" onClick={() => readOne(id)} disabled={read}>Mark read</Button><Button variant="ghost" onClick={() => remove(id)}>Delete</Button></div></div></Card>
          })}</div>
          {!filtered.length ? <EmptyState title="No notifications yet." /> : null}
        </>
      ) : null}
    </>
  )
}

export default NotificationPage
