export const queryKeys = {
  me: ["auth", "me"] as const,
  workspace: ["workspace"] as const,
  publicSubscriptionPlans: ["subscription-plans", "public"] as const,
  activeSubscriptionPlans: ["subscription-plans", "active"] as const,
  workspaceRegistration: (id?: string) => ["public", "workspace-registration", id ?? "current"] as const,
  publicPaymentStatus: (paymentCode: string) => ["public", "payments", paymentCode] as const,
  payment: (paymentCode: string) => ["public", "payments", paymentCode] as const,
  adminPayments: (filters?: Record<string, unknown>) => ["admin", "payments", filters ?? {}] as const,
  adminPayment: (paymentId: string) => ["admin", "payments", paymentId] as const,
  adminAuditLogs: (filters?: Record<string, unknown>) => ["admin", "audit-logs", filters ?? {}] as const,
  adminMonitoring: ["admin", "monitoring"] as const,
  adminWorkspaces: ["admin", "workspaces"] as const,
  adminWorkspaceDetail: (id: string) => ["admin", "workspaces", id] as const,
  adminBusinessOwners: (workspaceId: string) => ["admin", "workspaces", workspaceId, "business-owners"] as const,
  adminSubscriptionPlans: ["admin", "subscription-plans"] as const,
  adminWorkspaceRegistrations: ["admin", "workspace-registrations"] as const,
  adminBusinessFeedback: ["admin", "business-feedback"] as const,
  employees: ["employees"] as const,
  employee: (id: string) => ["employees", id] as const,
  employeeWorkload: (id: string) => ["analytics", "employees", id, "workload"] as const,
  tasks: ["tasks"] as const,
  task: (id: string) => ["tasks", id] as const,
  taskUpdates: (id: string) => ["tasks", id, "updates"] as const,
  taskAttachments: (id: string) => ["tasks", id, "attachments"] as const,
  taskRecommendation: (kind: "individual" | "team-leaders" | "team-members") => ["tasks", "recommendations", kind] as const,
  aiRecommendationExplanation: (signature: string, kind: string) => ["ai", "recommendation-explanation", signature, kind] as const,
  aiSelectionExplanation: (signature: string) => ["ai", "selection-explanation", signature] as const,
  aiEstimatedHours: (signature: string) => ["ai", "estimated-hours", signature] as const,
  aiWorkloadRisk: (employeeId: string, period: string) => ["ai", "workload-risk", employeeId, period] as const,
  aiEmployeeReport: (employeeId: string, period: string) => ["ai", "employee-report", employeeId, period] as const,
  hrEmployees: ["hr", "employees"] as const,
  departments: (filters?: Record<string, unknown>) => ["hr", "departments", filters ?? {}] as const,
  department: (id: string) => ["hr", "departments", id] as const,
  businessPositions: (filters?: Record<string, unknown>) => ["hr", "business-positions", filters ?? {}] as const,
  businessPosition: (id: string) => ["hr", "business-positions", id] as const,
  hrJobPositions: ["hr", "job-positions"] as const,
  managerTasks: ["manager", "tasks"] as const,
  monthlyWorkload: (year: number, month: number) => ["workload", "monthly", year, month] as const,
  groupRecommendations: ["ai", "recommendations", "group"] as const,
  reports: ["daily-reports"] as const,
  notifications: ["notifications"] as const,
  ownerDashboard: ["analytics", "owner-dashboard"] as const,
  workload: ["analytics", "workload"] as const,
  ai: ["ai"] as const,
  aiSection: (section: string) => ["ai", section] as const,
  aiHistory: (filters?: Record<string, unknown>) => ["ai", "history", filters ?? {}] as const,
  taskAnalysis: (taskId = "draft") => ["ai", "task-analysis", taskId] as const,
  businessOwnerOperationalSummary: ["ai", "business-owner-operational-summary"] as const,
  platformAiSummary: ["admin", "ai", "platform-summary"] as const,
};
