import { routes } from './routes.js'

export const roles = {
  admin: {
    id: 'admin',
    label: 'Quản trị hệ thống',
    shortLabel: 'Admin',
    accent: 'purple',
    subtitle: 'Hệ thống',
    switchDescription: 'Quản trị nền tảng',
    headerBadge: 'SYSTEM ADMIN',
    user: { name: 'System Admin', title: 'Quản trị hệ thống', initials: 'SA' },
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-100 dark:bg-purple-950/40 dark:text-purple-200 dark:border-purple-900',
    breadcrumb: 'Quản trị hệ thống',
    searchPlaceholder: 'Tìm tổ chức, tài khoản, cấu hình...',
    sidebarSearchPlaceholder: 'Tìm hệ thống...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.organizations, routes.users, routes.settings, routes.monitoring, routes.notifications],
    menuSections: [
      {
        title: 'QUẢN TRỊ HỆ THỐNG',
        items: [
          { label: 'Tổng quan hệ thống', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Tổ chức', path: routes.organizations, icon: 'building' },
          { label: 'Tài khoản người dùng', path: routes.users, icon: 'users' },
          { label: 'Cấu hình hệ thống', path: routes.settings, icon: 'settings' },
          { label: 'Audit log', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Thông báo hệ thống', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  director: {
    id: 'director',
    label: 'Giám đốc',
    shortLabel: 'Director',
    accent: 'blue',
    subtitle: 'Tổ chức',
    switchDescription: 'Điều hành organization',
    headerBadge: 'GIÁM ĐỐC',
    user: { name: 'Director', title: 'Người điều hành tổ chức', initials: 'DR' },
    badgeClass: 'bg-sky-50 text-sky-700 border-sky-100 dark:bg-sky-950/40 dark:text-sky-200 dark:border-sky-900',
    breadcrumb: 'Giám đốc',
    searchPlaceholder: 'Tìm dự án, team, insight...',
    sidebarSearchPlaceholder: 'Tìm organization...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.projects, routes.users, routes.teams, routes.employees, routes.analytics, routes.aiInsights, routes.monitoring, routes.notifications, routes.settings],
    menuSections: [
      {
        title: 'ĐIỀU HÀNH TỔ CHỨC',
        items: [
          { label: 'Tổng quan điều hành', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Sức khỏe tổ chức', path: routes.projects, icon: 'projects' },
          { label: 'Quản lý manager', path: routes.users, icon: 'users' },
          { label: 'Team trong tổ chức', path: routes.teams, icon: 'users' },
          { label: 'Nhân viên', path: routes.employees, icon: 'profile' },
          { label: 'Gợi ý AI', path: routes.aiInsights, icon: 'ai' },
          { label: 'Trạng thái đồng bộ', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Cài đặt', path: routes.settings, icon: 'settings' },
          { label: 'Thông báo', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  manager: {
    id: 'manager',
    label: 'Quản lý',
    shortLabel: 'Manager',
    accent: 'cyan',
    subtitle: 'Team / Project',
    switchDescription: 'Quản lý team/project',
    headerBadge: 'QUẢN LÝ',
    user: { name: 'Manager', title: 'Quản lý team', initials: 'MG' },
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-100 dark:bg-cyan-950/40 dark:text-cyan-200 dark:border-cyan-900',
    breadcrumb: 'Quản lý',
    searchPlaceholder: 'Tìm workload, dự án, insight...',
    sidebarSearchPlaceholder: 'Tìm team...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.integrations, routes.projects, routes.events, routes.reports, routes.employees, routes.analytics, routes.aiInsights, routes.monitoring, routes.notifications],
    menuSections: [
      {
        title: 'VẬN HÀNH TEAM',
        items: [
          { label: 'Tổng quan quản lý', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Trung tâm tích hợp', path: routes.integrations, icon: 'integration' },
          { label: 'Dự án đã import', path: routes.projects, icon: 'projects' },
          { label: 'Repository đã import', path: routes.events, icon: 'events' },
          { label: 'Ánh xạ danh tính', path: routes.reports, icon: 'users' },
          { label: 'Tài khoản nhân viên', path: routes.employees, icon: 'profile' },
          { label: 'Phân tích', path: routes.analytics, icon: 'analytics' },
          { label: 'Gợi ý AI', path: routes.aiInsights, icon: 'ai' },
          { label: 'Lịch sử đồng bộ', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Thông báo', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  employee: {
    id: 'employee',
    label: 'Nhân viên',
    shortLabel: 'Employee',
    accent: 'slate',
    subtitle: 'Cá nhân',
    switchDescription: 'Không gian cá nhân',
    headerBadge: 'NHÂN VIÊN',
    user: { name: 'Employee', title: 'Nhân viên', initials: 'NV' },
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700',
    breadcrumb: 'Nhân viên',
    searchPlaceholder: 'Tìm workload, insight, thông báo của tôi...',
    sidebarSearchPlaceholder: 'Tìm cá nhân...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.tasks, routes.events, routes.analytics, routes.aiInsights, routes.notifications, routes.profile],
    menuSections: [
      {
        title: 'KHÔNG GIAN CÁ NHÂN',
        items: [
          { label: 'Tổng quan cá nhân', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Công việc của tôi', path: routes.tasks, icon: 'tasks' },
          { label: 'Đóng góp của tôi', path: routes.events, icon: 'events' },
          { label: 'Workload cá nhân', path: routes.analytics, icon: 'analytics' },
          { label: 'Phản hồi AI', path: routes.aiInsights, icon: 'ai' },
          { label: 'Thông báo của tôi', path: routes.notifications, icon: 'notifications', notificationBadge: true },
          { label: 'Hồ sơ', path: routes.profile, icon: 'profile' },
        ],
      },
    ],
  },
}

export const roleOptions = Object.entries(roles).map(([value, config]) => ({
  value,
  label: config.label,
  shortLabel: config.shortLabel,
  description: config.switchDescription,
}))
