import { routes } from './routes.js'

export const roles = {
  admin: {
    id: 'admin',
    label: 'Quản trị hệ thống',
    shortLabel: 'Admin',
    accent: 'purple',
    subtitle: 'Hệ thống',
    switchDescription: 'Quản trị nền tảng',
    headerBadge: 'SYSTEM ADMIN',
    user: { name: 'System Admin', title: 'Quản trị hệ thống', initials: 'SA' },
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-100 dark:bg-purple-950/40 dark:text-purple-200 dark:border-purple-900',
    breadcrumb: 'Quản trị hệ thống',
    searchPlaceholder: 'Tìm tổ chức, tài khoản, cấu hình...',
    sidebarSearchPlaceholder: 'Tìm hệ thống...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.organizations, routes.users, routes.settings, routes.monitoring, routes.notifications],
    menuSections: [
      {
        title: 'QUẢN TRỊ HỆ THỐNG',
        items: [
          { label: 'Tổng quan hệ thống', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Tổ chức', path: routes.organizations, icon: 'building' },
          { label: 'Tài khoản', path: routes.users, icon: 'users' },
          { label: 'Cấu hình hệ thống', path: routes.settings, icon: 'settings' },
          { label: 'Nhật ký hệ thống', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Thông báo hệ thống', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  director: {
    id: 'director',
    label: 'Director',
    shortLabel: 'Director',
    accent: 'blue',
    subtitle: 'Tổ chức',
    switchDescription: 'Điều hành organization',
    headerBadge: 'DIRECTOR',
    user: { name: 'Director', title: 'Người điều hành tổ chức', initials: 'DR' },
    badgeClass: 'bg-sky-50 text-sky-700 border-sky-100 dark:bg-sky-950/40 dark:text-sky-200 dark:border-sky-900',
    breadcrumb: 'Director',
    searchPlaceholder: 'Tìm dự án, team, insight...',
    sidebarSearchPlaceholder: 'Tìm organization...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.projects, routes.analytics, routes.aiInsights, routes.integrations, routes.events, routes.monitoring, routes.notifications, routes.reports],
    menuSections: [
      {
        title: 'ĐIỀU HÀNH TỔ CHỨC',
        items: [
          { label: 'Organization Dashboard', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Sức khỏe dự án', path: routes.projects, icon: 'projects' },
          { label: 'Phân tích team', path: routes.analytics, icon: 'analytics' },
          { label: 'Phân tích GitHub', path: routes.events, icon: 'events' },
          { label: 'AI Insights', path: routes.aiInsights, icon: 'ai' },
          { label: 'Tích hợp', path: routes.integrations, icon: 'integration' },
          { label: 'Ánh xạ danh tính', path: routes.reports, icon: 'users' },
          { label: 'Lịch sử đồng bộ', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Nhật ký hệ thống', path: routes.monitoring, icon: 'reports' },
          { label: 'Thông báo', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  manager: {
    id: 'manager',
    label: 'Manager',
    shortLabel: 'Manager',
    accent: 'cyan',
    subtitle: 'Team / Project',
    switchDescription: 'Quản lý team/project',
    headerBadge: 'MANAGER',
    user: { name: 'Manager', title: 'Quản lý team', initials: 'MG' },
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-100 dark:bg-cyan-950/40 dark:text-cyan-200 dark:border-cyan-900',
    breadcrumb: 'Manager',
    searchPlaceholder: 'Tìm workload, dự án, insight...',
    sidebarSearchPlaceholder: 'Tìm team...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.projects, routes.analytics, routes.aiInsights, routes.integrations, routes.events, routes.monitoring, routes.notifications],
    menuSections: [
      {
        title: 'VẬN HÀNH TEAM',
        items: [
          { label: 'Team Dashboard', path: routes.dashboard, icon: 'dashboard' },
          { label: 'Sức khỏe dự án', path: routes.projects, icon: 'projects' },
          { label: 'Workload', path: routes.analytics, icon: 'analytics' },
          { label: 'Phân tích GitHub', path: routes.events, icon: 'events' },
          { label: 'AI Insights', path: routes.aiInsights, icon: 'ai' },
          { label: 'Tích hợp', path: routes.integrations, icon: 'integration' },
          { label: 'Ánh xạ danh tính', path: routes.reports, icon: 'users' },
          { label: 'Lịch sử đồng bộ', path: routes.monitoring, icon: 'monitoring' },
          { label: 'Thông báo', path: routes.notifications, icon: 'notifications', notificationBadge: true },
        ],
      },
    ],
  },
  employee: {
    id: 'employee',
    label: 'Nhân viên',
    shortLabel: 'Employee',
    accent: 'slate',
    subtitle: 'Cá nhân',
    switchDescription: 'Không gian cá nhân',
    headerBadge: 'EMPLOYEE',
    user: { name: 'Employee', title: 'Nhân viên', initials: 'NV' },
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700',
    breadcrumb: 'Nhân viên',
    searchPlaceholder: 'Tìm workload, insight, thông báo của tôi...',
    sidebarSearchPlaceholder: 'Tìm cá nhân...',
    createActions: [],
    allowedRoutes: [routes.dashboard, routes.analytics, routes.aiInsights, routes.notifications, routes.profile],
    menuSections: [
      {
        title: 'KHÔNG GIAN CÁ NHÂN',
        items: [
          { label: 'My Dashboard', path: routes.dashboard, icon: 'dashboard' },
          { label: 'My Workload', path: routes.analytics, icon: 'analytics' },
          { label: 'My AI Insights', path: routes.aiInsights, icon: 'ai' },
          { label: 'My Notifications', path: routes.notifications, icon: 'notifications', notificationBadge: true },
          { label: 'Hồ sơ', path: routes.profile, icon: 'profile' },
        ],
      },
    ],
  },
}

export const roleOptions = Object.entries(roles).map(([value, config]) => ({
  value,
  label: config.label,
  shortLabel: config.shortLabel,
  description: config.switchDescription,
}))
