export const routes = {
  landing: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  tasks: '/tasks',
  employees: '/employees',
  teams: '/teams',
  sprints: '/sprints',
  events: '/events',
  analytics: '/analytics',
  aiInsights: '/ai-insights',
  attendance: '/attendance',
  leave: '/leave',
  notifications: '/notifications',
  settings: '/settings',
  organizations: '/organizations',
  users: '/users',
  integrations: '/integrations',
  monitoring: '/monitoring',
  reports: '/reports',
  recruitment: '/recruitment',
  profile: '/profile',
}
